#ifndef INC_ERA_SERIAL_BLE_TRANSP_ESP32_HPP_
#define INC_ERA_SERIAL_BLE_TRANSP_ESP32_HPP_

#define ERA_BLE_TASK_PRIORITY (configMAX_PRIORITIES - 10)

#include <BLE/ERaSerialBLETransp.hpp>

#endif /* INC_ERA_SERIAL_BLE_TRANSP_ESP32_HPP_ */
