#ifndef INC_DEFINE_CLUSTER_ZIGBEE_HPP_
#define INC_DEFINE_CLUSTER_ZIGBEE_HPP_

namespace ZigbeeNamespace {

    enum ProfileIDT {
        ZCL_PROFILE_ZB_STANDARD_MIN = 0x0000,
        /* Note: Legacy profile range does not include HA (0x0104) */
        ZCL_PROFILE_LEGACY_MIN = 0x0101,
        ZCL_PROFILE_HOME_AUTOMATION = 0x0104,
        ZCL_PROFILE_COMMERCIAL_BUILDING_AUTOMATION = 0x0105,
        ZCL_PROFILE_TELECOM_APPLICATION = 0x0107,
        ZCL_PROFILE_LEGACY_MAX = 0x0108,
        ZCL_PROFILE_SMART_ENERGY = 0x0109,
        ZCL_PROFILE_RETAIL_SERVICES = 0x010A,
        ZCL_PROFILE_GREEN_POWER = 0xA1E0,
        ZCL_PROFILE_TP2 = 0x7f01, /* ZigBee Test Profile #2 Profile Id */
        ZCL_PROFILE_ZB_STANDARD_MAX = 0x7fff,

        ZCL_PROFILE_MFR_SPECIFIC_MIN = 0xc000,
        ZCL_PROFILE_ZLL = 0xc05e,
        ZCL_PROFILE_C4 = 0xc25d,
        ZCL_PROFILE_WILDCARD = 0xffff /* Wildcard Profile ID */
    };

    enum DeviceIDT {
        ZCL_DEVICE_ONOFF_SWITCH = 0x0000,
        ZCL_DEVICE_LEVEL_SWITCH = 0x0001,
        ZCL_DEVICE_ONOFF_OUTPUT = 0x0002,
        ZCL_DEVICE_LEVEL_OUTPUT = 0x0003,
        ZCL_DEVICE_SCENE_SELECTOR = 0x0004,
        ZCL_DEVICE_CONFIG_TOOL = 0x0005,
        ZCL_DEVICE_REMOTE_CONTROL = 0x0006,
        ZCL_DEVICE_COMBINED_INTERFACE = 0x0007,
        ZCL_DEVICE_RANGE_EXTENDER = 0x0008,
        ZCL_DEVICE_MAINS_POWER_OUTLET = 0x0009,
        ZCL_DEVICE_DOOR_LOCK = 0x000a,
        ZCL_DEVICE_DOOR_LOCK_CONTROLLER = 0x000b,
        ZCL_DEVICE_SIMPLE_SENSOR = 0x000c,
        ZCL_DEVICE_DATA_COLLECTION_UNIT = 0x0010,
        ZCL_DEVICE_ZIGBEE_SIM_CARD = 0x0020,
        ZCL_DEVICE_ZIGBEE_MOBILE_TERMINAL = 0x0021,
        ZCL_DEVICE_ZIGBEE_GLOBAL_PLATFORM_CARD = 0x0026, /* same as  */
        ZCL_DEVICE_CUSTOMER_HANDHELD_DEVICE = 0x0030,
        ZCL_DEVICE_RETAIL_ASSOCIATE_HANDHELD_DEVICE = 0x0031,
        ZCL_DEVICE_INTELLIGENT_SHOPPING_CART = 0x0032,
        ZCL_DEVICE_ELECTRONIC_SHELF_LABEL = 0x0033,
        ZCL_DEVICE_CUSTOMER_INFORMATION_POINT = 0x0034,
        ZCL_DEVICE_CUSTOMER_CARD = 0x0035,
        ZCL_DEVICE_CONSTRUCTED_BACNET_DEVICE = 0x004a,
        ZCL_DEVICE_BACNET_TUNNELED_DEVICE = 0x004b,
        ZCL_DEVICE_HOME_GATEWAY = 0x0050,
        ZCL_DEVICE_SMART_PLUG = 0x0051,
        ZCL_DEVICE_WHITE_GOODS = 0x0052,
        ZCL_DEVICE_METER_INTERFACE = 0x0053,
        ZCL_DEVICE_ZGP_PROXY = 0x0060,
        ZCL_DEVICE_ZGP_PROXY_BASIC = 0x0061,
        ZCL_DEVICE_ZGP_TARGET_PLUS = 0x0062,
        ZCL_DEVICE_ZGP_TARGET = 0x0063,
        ZCL_DEVICE_ZGP_COMMISSIONING_TOOL = 0x0064,
        ZCL_DEVICE_ZGP_COMBO = 0x0065,
        ZCL_DEVICE_ZGP_COMBO_BASIC = 0x0066,
        ZCL_DEVICE_ENVIRONMENTAL_SENSOR = 0x0067,

        /* Lighting and Occupancy (0x0100) */
        ZCL_DEVICE_ONOFF_LIGHT = 0x0100,
        ZCL_DEVICE_DIMMABLE_LIGHT = 0x0101,
        ZCL_DEVICE_COLOR_DIMMABLE_LIGHT = 0x0102,
        ZCL_DEVICE_ONOFF_LIGHT_SWITCH = 0x0103,
        ZCL_DEVICE_ONOFF_DIMMER_SWITCH = 0x0104,
        ZCL_DEVICE_ONOFF_COLOR_DIMMER_SWITCH = 0x0105,
        ZCL_DEVICE_ONOFF_LIGHT_SENSOR = 0x0106,
        ZCL_DEVICE_ONOFF_OCCUPANCY_SENSOR = 0x0107,
        /* EXEGIN - add more from Lighting and Occupancy Device Spec */

        /* IAS (0x0400) */
        ZCL_DEVICE_IAS_CONTROL_AND_INDICATING_EQUIPMENT = 0x0400,
        ZCL_DEVICE_IAS_ANCILLARY_CONTROL_EQUIPMENT = 0x0401,
        ZCL_DEVICE_IAS_ZONE = 0x0402,
        ZCL_DEVICE_IAS_WARNING_DEVICE = 0x0403,

        /* Smart Energy device identifiers. (0x0500) */
        ZCL_DEVICE_ESP = 0x0500,
        ZCL_DEVICE_METER = 0x0501,
        ZCL_DEVICE_IN_HOME_DISPLAY = 0x0502,
        ZCL_DEVICE_PCT = 0x0503,
        ZCL_DEVICE_LOAD_CONTROL = 0x0504,
        ZCL_DEVICE_SMART_APPLIANCE = 0x0505,
        ZCL_DEVICE_PREPAYMENT_TERMINAL = 0x0506,
        ZCL_DEVICE_PHYSICAL_DEVICE = 0x0507,
        ZCL_DEVICE_REMOTE_COMMUNICATIONS_DEVICE = 0x0508,
        ZCL_DEVICE_ERL_INTERFACE = 0x0509,

        /* Lighting and Occupancy Continued (0x0800) */
        ZCL_DEVICE_COLOR_CONTROLLER = 0x0800,
        ZCL_DEVICE_COLOR_SCENE_CONTROLLER = 0x0810,
        ZCL_DEVICE_NON_COLOR_CONTROLLER = 0x0820,
        ZCL_DEVICE_NON_COLOR_SCENE_CONTROLLER = 0x0830,
        ZCL_DEVICE_CONTROL_BRIDGE = 0x0840,
        ZCL_DEVICE_ONOFF_SENSOR = 0x0850 /* aka Door Sensor? */
    };

    enum ClusterIDT {
        /* General cluster identifiers. */
        ZCL_CLUSTER_BASIC = 0x0000,
        ZCL_CLUSTER_POWER_CONFIG = 0x0001,
        ZCL_CLUSTER_ONOFF = 0x0006,
        ZCL_CLUSTER_LEVEL_CONTROL = 0x0008,
        ZCL_CLUSTER_MULTISTATE_INPUT_BASIC = 0x0012,
        ZCL_CLUSTER_OTA_UPGRADE = 0x0019,
        ZCL_CLUSTER_POLL_CONTROL = 0x0020,
        ZCL_CLUSTER_GREEN_POWER = 0x0021,

        /* Measurement Cluster IDs */
        ZCL_CLUSTER_MEAS_TEMPERATURE = 0x0402,
        ZCL_CLUSTER_MEAS_PRESSURE = 0x0403,
        ZCL_CLUSTER_MEAS_HUMIDITY = 0x0405,

        /* Security Cluster IDs */
        ZCL_CLUSTER_SECURITY_IAS_ZONE = 0x0500,

        NO_CLUSTER_ID = 0x2706
    };

};

#endif /* INC_DEFINE_CLUSTER_ZIGBEE_HPP_ */
