#ifndef INC_ERA_MODBUS_STREAM_DEFINE_HPP_
#define INC_ERA_MODBUS_STREAM_DEFINE_HPP_

enum ModbusStreamStateT {
    MB_STREAM_STATE_BEGIN = 0,
    MB_STREAM_STATE_ADDR = 1,
    MB_STREAM_STATE_FUNC = 2,
    MB_STREAM_STATE_DATA = 3,
    MB_STREAM_STATE_END = 4
};

#endif /* INC_ERA_MODBUS_STREAM_DEFINE_HPP_ */
