#ifndef INC_ERA_SIMPLE_ZIGBEE_ETHERNET_SSL_HPP_
#define INC_ERA_SIMPLE_ZIGBEE_ETHERNET_SSL_HPP_

#define ERA_ZIGBEE

#include <ERaSimpleEthernetSSL.hpp>

#endif /* INC_ERA_SIMPLE_ZIGBEE_ETHERNET_SSL_HPP_ */
