#ifndef INC_ERA_SIMPLE_MODBUS_REALTEK_WIFI_HPP_
#define INC_ERA_SIMPLE_MODBUS_REALTEK_WIFI_HPP_

#define ERA_MODBUS

#include <ERaSimpleRealtekWiFi.hpp>

#endif /* INC_ERA_SIMPLE_MODBUS_REALTEK_WIFI_HPP_ */
