#ifndef INC_ERA_SIMPLE_MODBUS_ESP32_SSL_WIFI_HPP_
#define INC_ERA_SIMPLE_MODBUS_ESP32_SSL_WIFI_HPP_

#define ERA_MODBUS

#include <ERaSimpleEsp32SSLWiFi.hpp>

#endif /* INC_ERA_SIMPLE_MODBUS_ESP32_SSL_WIFI_HPP_ */
