#ifndef INC_ERA_SIMPLE_MODBUS_ETHERNET_ENC_HPP_
#define INC_ERA_SIMPLE_MODBUS_ETHERNET_ENC_HPP_

#define ERA_MODBUS

#include <ERaSimpleEthernetENC.hpp>

#endif /* INC_ERA_SIMPLE_MODBUS_ETHERNET_ENC_HPP_ */
