#ifndef INC_ERA_SIMPLE_ZIGBEE_STM32_SSL_WIZ_HPP_
#define INC_ERA_SIMPLE_ZIGBEE_STM32_SSL_WIZ_HPP_

#define ERA_ZIGBEE

#include <ERaSimpleStm32SSLWiz.hpp>

#endif /* INC_ERA_SIMPLE_ZIGBEE_STM32_SSL_WIZ_HPP_ */
