#ifndef INC_ERA_SIMPLE_MODBUS_ESP8266_SSL_HPP_
#define INC_ERA_SIMPLE_MODBUS_ESP8266_SSL_HPP_

#define ERA_MODBUS

#include <ERaSimpleEsp8266SSL.hpp>

#endif /* INC_ERA_SIMPLE_MODBUS_ESP8266_SSL_HPP_ */
