#ifndef INC_ERA_SIMPLE_ZIGBEE_STM32_SSL_ETHERNET_HPP_
#define INC_ERA_SIMPLE_ZIGBEE_STM32_SSL_ETHERNET_HPP_

#define ERA_ZIGBEE

#include <ERaSimpleStm32SSLEthernet.hpp>

#endif /* INC_ERA_SIMPLE_ZIGBEE_STM32_SSL_ETHERNET_HPP_ */
