#ifndef INC_ERA_SIMPLE_MODBUS_STM32_SSL_WIZ_HPP_
#define INC_ERA_SIMPLE_MODBUS_STM32_SSL_WIZ_HPP_

#define ERA_MODBUS

#include <ERaSimpleStm32SSLWiz.hpp>

#endif /* INC_ERA_SIMPLE_MODBUS_STM32_SSL_WIZ_HPP_ */
