#ifndef INC_ERA_SIMPLE_ZIGBEE_STM32_ETHERNET_HPP_
#define INC_ERA_SIMPLE_ZIGBEE_STM32_ETHERNET_HPP_

#define ERA_ZIGBEE

#include <ERaSimpleStm32Ethernet.hpp>

#endif /* INC_ERA_SIMPLE_ZIGBEE_STM32_ETHERNET_HPP_ */
