#ifndef INC_ERA_SIMPLE_MODBUS_STM32_ETHERNET_HPP_
#define INC_ERA_SIMPLE_MODBUS_STM32_ETHERNET_HPP_

#define ERA_MODBUS

#include <ERaSimpleStm32Ethernet.hpp>

#endif /* INC_ERA_SIMPLE_MODBUS_STM32_ETHERNET_HPP_ */
