#ifndef INC_ERA_SIMPLE_MODBUS_ARDUINO_MBED_ETHERNET_HPP_
#define INC_ERA_SIMPLE_MODBUS_ARDUINO_MBED_ETHERNET_HPP_

#define ERA_MODBUS

#include <ERaSimpleArduinoMbedEthernet.hpp>

#endif /* INC_ERA_SIMPLE_MODBUS_ARDUINO_MBED_ETHERNET_HPP_ */
