#ifndef INC_ERA_SIMPLE_MODBUS_ETHERNET_SSL_HPP_
#define INC_ERA_SIMPLE_MODBUS_ETHERNET_SSL_HPP_

#define ERA_MODBUS

#include <ERaSimpleEthernetSSL.hpp>

#endif /* INC_ERA_SIMPLE_MODBUS_ETHERNET_SSL_HPP_ */
