#ifndef INC_ERA_SIMPLE_MODBUS_ESP32_MULTI_HPP_
#define INC_ERA_SIMPLE_MODBUS_ESP32_MULTI_HPP_

#define ERA_MODBUS

#include <ERaSimpleEsp32Multi.hpp>

#endif /* INC_ERA_SIMPLE_MODBUS_ESP32_MULTI_HPP_ */
