#ifndef INC_ERA_SIMPLE_ZIGBEE_ARDUINO_MBED_HPP_
#define INC_ERA_SIMPLE_ZIGBEE_ARDUINO_MBED_HPP_

#define ERA_ZIGBEE

#include <ERaSimpleArduinoMbed.hpp>

#endif /* INC_ERA_SIMPLE_ZIGBEE_ARDUINO_MBED_HPP_ */
