#ifndef INC_ERA_SIMPLE_MODBUS_RP2040_WIFI_HPP_
#define INC_ERA_SIMPLE_MODBUS_RP2040_WIFI_HPP_

#define ERA_MODBUS

#include <ERaSimpleRp2040WiFi.hpp>

#endif /* INC_ERA_SIMPLE_MODBUS_RP2040_WIFI_HPP_ */
