#ifndef INC_ERA_SIMPLE_MODBUS_STM32_SSL_ETHERNET_HPP_
#define INC_ERA_SIMPLE_MODBUS_STM32_SSL_ETHERNET_HPP_

#define ERA_MODBUS

#include <ERaSimpleStm32SSLEthernet.hpp>

#endif /* INC_ERA_SIMPLE_MODBUS_STM32_SSL_ETHERNET_HPP_ */
