#ifndef INC_ERA_SIMPLE_ZIGBEE_ESP32_MULTI_HPP_
#define INC_ERA_SIMPLE_ZIGBEE_ESP32_MULTI_HPP_

#define ERA_ZIGBEE

#include <ERaSimpleEsp32Multi.hpp>

#endif /* INC_ERA_SIMPLE_ZIGBEE_ESP32_MULTI_HPP_ */
