#ifndef INC_ERA_SIMPLE_ZIGBEE_ETHERNET_ENC_HPP_
#define INC_ERA_SIMPLE_ZIGBEE_ETHERNET_ENC_HPP_

#define ERA_ZIGBEE

#include <ERaSimpleEthernetENC.hpp>

#endif /* INC_ERA_SIMPLE_ZIGBEE_ETHERNET_ENC_HPP_ */
