#ifndef INC_ERA_SIMPLE_ZIGBEE_ESP32_SSL_WIZ_HPP_
#define INC_ERA_SIMPLE_ZIGBEE_ESP32_SSL_WIZ_HPP_

#define ERA_ZIGBEE

#include <ERaSimpleEsp32SSLWiz.hpp>

#endif /* INC_ERA_SIMPLE_ZIGBEE_ESP32_SSL_WIZ_HPP_ */
