#ifndef INC_ERA_SIMPLE_MODBUS_RP2040_SSL_WIZ_HPP_
#define INC_ERA_SIMPLE_MODBUS_RP2040_SSL_WIZ_HPP_

#define ERA_MODBUS

#include <ERaSimpleRp2040SSLWiz.hpp>

#endif /* INC_ERA_SIMPLE_MODBUS_RP2040_SSL_WIZ_HPP_ */
