#ifndef INC_ERA_SIMPLE_ZIGBEE_ESP32_SSL_WIFI_HPP_
#define INC_ERA_SIMPLE_ZIGBEE_ESP32_SSL_WIFI_HPP_

#define ERA_ZIGBEE

#include <ERaSimpleEsp32SSLWiFi.hpp>

#endif /* INC_ERA_SIMPLE_ZIGBEE_ESP32_SSL_WIFI_HPP_ */
